language: php

php:
  - 5.6
  - 7.0
  - 7.1

before_script:
  - composer install --no-interaction --no-scripts

env:
  - APP_KEY=base64:oKkca01Gaxi9n+4iJlF6VL1QIHp49Ln6VTa6N61O4Ws=

script:
  - vendor/bin/phpunit
